repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: local
    hooks:
      - id: radon
        name: radon complexity
        entry: radon
        language: system
        types: [python]
        args: ["cc", "-a", "-s", "src/"]

  - repo: https://github.com/fpgmaas/deptry
    rev: 0.23.0
    hooks:
      - id: deptry
        args:
          - --requirements-files=requirements.txt
          - --known-first-party=src

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        args:
          - src
          - dwit.py

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: ["--fix"]